### ISSUE TITLE
Imagine/Imagine Version

### ISSUE THREAD

**Issue by brili** [CodeSleeve/stapler#105]
Can we add to composer.json "imagine/imagine": "~0.6.2" , instead of ~0.5.0 because they have added blur effect there and bugfixes

**Comment by DavidPhilip** [comment]
+++

**Comment by mouhsinelonly** [comment]
+1

**Comment by mouhsinelonly** [comment]
imagine/imagine is not updated yet to 0.6.2 using dev-master
