### ISSUE TITLE
Custom Interpolator

### ISSUE THREAD

**Issue by drtzack** [CodeSleeve/stapler#107]
I have a column for localization. So it could be nice if I can store files relative to column which keeps locale.

For example

/upload/de/slider/1.png
/upload/en/slider/1.png

**Comment by jimmyko** [comment]
+1. I want to know if there is a way to extend the interpolator.

**Comment by hackel** [comment]
I was trying to figure out how to do this as well.  The interpolation system is very inflexible.  It looks like the way to do it would be to have Codesleeve\Stapler\Stapler::getInterpolatorInstance check for a config value with a custom Interpolator class.  We would also need to create an Interpolator interface for such classes to implement.

Another approach, which might be both easier and more elegant: allow to define custom interpolation classes in the config file that each have a handle() method which returns the interpolated value.  Then the default Interpolator class could check for these as well as the built-in ones.  I think this is the approach I will take and make a PR for it.  Any comments on this approach?

**Comment by tabennett** [comment]
I've implemented this in 1.1.0 using design by contract. You can edit the bindings.php config file to change the concrete implementation that's used by Stapler when creating an interpolator instance. Create a class that implements `Codesleeve\Stapler\Interfaces\Interpolator`.and you can add as many custom interpolations as you like.
