### ISSUE TITLE
jpeg_quality has no effect

### ISSUE THREAD

**Issue by gpluess** [CodeSleeve/stapler#108]
I just noticed that ```jpeg_quality```has no effect on my uploaded images. They all have the same file size after they are saved by Stapler.

This is my config:
```
'test1' => [
    'dimensions' => '600x600',
    'convert_options' => ['jpeg_quality' => 100]
],
'test2' => [
    'dimensions' => '600x600',
    'convert_options' => ['jpeg_quality' => 1]
]
```

Any ideas?

**Comment by gpluess** [comment]
Any suggestions on this one?

**Comment by ByUsKevin** [comment]
Same problem...

**Comment by ByUsKevin** [comment]
I had the same problem and I just found the solution. 
Use 'quality' instead of 'jpeg_quality'  (as you can see here in the examples : https://github.com/CodeSleeve/stapler/blob/master/docs/examples.md )

**Comment by gpluess** [comment]
Awesome, thanks for finding this :+1:
