### ISSUE TITLE
Abort changes to attachment

### ISSUE THREAD

**Issue by davidwinter** [CodeSleeve/stapler#121]
Say a model doesn't pass validation, and you want to abort the uploaded image, and revert back to the original so that in your views, when calling `->url()` everything still works.

At the moment, I'm having to do something like this:

```php
// if validation has failed

$keys = array(
	'file_name', 
	'file_size', 
	'content_type', 
	'updated_at',
);

$image = 'public_image';

foreach ($keys as $key) {
	$model->{$image . '_' . $key} 
		= $model->getOriginal($image . '_' . $key);
}
```

Would it be a good idea to add an `abort` method or something similar to get the original values back?

**Comment by chrisatomix** [comment]
Just came across this issue too, it's causing me some serious grief. I don't want the database to change unless the photo is valid. If the user uploads a PDF or Word Document, it should display an error and leave the current photo intact.

Currently it tries to display a thumbnail of the broken image.

**Comment by tabennett** [comment]
What validation are you talking about here? Stapler doesn't update the database until the file is actually saved. If you're performing validation on the photo before you save, how is this happening? Also, it's not a good idea to be storing images and non-images files in the same table. You should try and break those out into two separate tables.
