### ISSUE TITLE
Attachment move fails when multiple styles are configured but attachment to be saved is not an image

### ISSUE THREAD

**Issue by aldas** [CodeSleeve/stapler#126]
I'm trying to use stapler for a following situation  - entity "User" has many "UserFiles" entities. UserFiles is stamplerInterface. 

I would like to hold images and documents with that class. This works fine when I remove "styles' array. Every uploaded file is moved to "original" subfolder. 
```
        $this->hasAttachedFile('file', []);
```

Things break when I would like to have images resized and at the same time store documents also in that model. So using configuration
```
        $this->hasAttachedFile('file', [
            'styles' => [
                'medium' => '300x300',
                'thumb' => '100x100'
            ]
        ]);
```
Throw exception in Attachment.flushWrites() as it tries to move file (document) multiple times (per configured style) and fail.  Internally styles are ordered as   'medium', 'thumb', 'original'. So on first for cycle document (attachment that is not an image) is moved and next cycle ('thumb') uses again  

´´´
            else {
                $file = $this->uploadedFile->getRealPath();
            }
´´´
else block and fail to move file. It was already move when 'medium" was cycled

Maybe "flushWrites()" should execute move only for 'original' style when attachment is not an image. ala have a check "if attachment is not an image and style is not original then continue forEach loop"

**Comment by tabennett** [comment]
This can't store documents and images in the same table. Stapler isn't made to work that way. You should break your documents (non-image files) out into their own table.
