### ISSUE TITLE
Issue when deleting files from S3

### ISSUE THREAD

**Issue by elimentz** [CodeSleeve/stapler#145]
I just upgraded my app from L4 to L5 and encountered an issue when deleting a file from S3. An exception is thrown when validating the delete request to S3: 

``` js
{"error":{"type":"InvalidArgumentException","message":"Found 1 error while validating the input provided
 for the DeleteObjects operation:\n[Delete] is missing and is a required parameter","file":"\/www
\/htdocs\/vendor\/aws\/aws-sdk-php\/src\/Api\/Validator.php","line":38}}
```

Which would seem very weird to me. I did check the message (see attachment) and as far as I can see, the [Delete] component is actually available. Any idea what this could be?

![screen shot 2015-09-29 at 16 50 23](https://cloud.githubusercontent.com/assets/1410811/10168195/0bd85dea-66cc-11e5-9704-2aca82f717c6.png)

I'm using the following stack:
- L5.1
- laravel-Stapler 1.0.05
- stapler 1.0.06
  aws/aws-sdk-php 3.4.0

Much appreciated

**Comment by argia-andreas** [comment]
@elimentz 
I think there is a problem with the version of S3Client. I think they changed the arguments for deleteObjects in version 3.*

I fixed it temporarily by changing the remove function in ```stapler/src/storage/s3.php``` to the following:
```
public function remove(array $filePaths)
    {
        if ($filePaths) {
            $this->s3Client->deleteObjects([
                                            'Bucket' => $this->attachedFile->s3_object_config['Bucket'],
                                            'Delete'  => [
                                                'Objects' => $this->getKeys($filePaths)]
                                            ]);
        }
    }
```

The Objects array needs to be inside a Delete array.

**Comment by elimentz** [comment]
I fixed the issue by downgrading the version of amazon aws to "~2.0", previously "~3.0". That solved the issue for me.

**Comment by neerajgoyal12** [comment]
did you do this in s3_client_config array with 'version' => '~2.0' instead of latest. ?

**Comment by elimentz** [comment]
No, I modified my composer file. the 2.0 refers to the composer tag, not the API version. See below

```js
// composer.json

"require": {
        "php": ">=5.6.0",
        "laravel/framework": "5.1.*",
        "aws/aws-sdk-php-laravel": "~2.0",                       <=== This is what you're looking for
        "codesleeve/laravel-stapler": "1.0.*"
    },
```

**Comment by neerajgoyal12** [comment]
thanks for your answer.

**Comment by elimentz** [comment]
Hate to bring this up again, but here I am. Due to new features, we actually need to use v3 of the Amazon SDK so this issue is popping up again. Could you please let me know if this is Amazon related or is the issue related to the package? I'd hate to bother the wrong people...

**Comment by laravelian** [comment]
I also very much need this fixed.  If I find an elegant solution I'll submit a PR

**Comment by tanigami** [comment]
+1

**Comment by Shane-Lessard** [comment]
Also in need of a fix for this. I'll try and put something together myself and do a PR, since this seems to be a long-standing issue.

**Comment by kevinschenkers** [comment]
Is there already a fix to use this along v3?

**Comment by tabennett** [comment]
This version of Stapler is not made to work with v3 of the S3 client. I'm sorry, but that's not going to change in the near future. I'm working on getting 2.0 released and it's built on top of flysystem, which does use the v3 client. You are more than welcome to test things out (it's currently sitting on the dev branch), but I'm still working on getting the documentation updated and there are some backwards compatibility breaking changes (e.g it requires php 7^ now).

**Comment by kyranb** [comment]
@tabennett I'm currently on V2, but would like to take advantage of Flysystem/v3.

Aside from requiring php7, are there any other key breaking changes I should look out for?

**Comment by kyranb** [comment]
@tabennett I'd like to try out 2.0 👍   Aside from the PHP 7 requirements, are there any other breaking changes?
