### ISSUE TITLE
edge use case: use stapler to  upload multiple files without stapling.

### ISSUE THREAD

**Issue by illuminate3** [CodeSleeve/stapler#157]
controller:

```
$images = Input::file('images');
foreach($images as $image)
{
	$image = Image::create($image);
}
```

error gets throw ...
```
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::create() must be of the type array, object given, called in 
```

if I use

```
	$image = Image::create($request->all());
```

No error but my database registers an insert without data and the folders are empty. 

Do you have any suggestions?

Thanks!

**Comment by tabennett** [comment]
You can't really use Eloquent like that. The ```create()``` method has an array type hint, so it has to have an array:
```php
/**
     * Save a new model and return the instance.
     *
     * @param  array  $attributes
     * @return static
     */
    public static function create(array $attributes = [])
    {
        $model = new static($attributes);

        $model->save();

        return $model;
    }
```

You need to wrap your uploaded file objects in an array. Assuming your Stapler attachment was named *foo*, it would look like this:
```php
$image = Image::create(['foo' => $image]);
```

Also, make sure that *foo* is in your ```$fillable``` array on your model.

**Comment by illuminate3** [comment]
Thank you!
Gonna have to meet up and get come BBQ or catfish :-)

The foo part is what did it!

Thanks
