### ISSUE TITLE
[Proposal] rename attachments

### ISSUE THREAD

**Issue by kdocki** [CodeSleeve/stapler#36]
It would be nice to be able to rename an attachment's name. If the attachment has already been saved it will rename the `<attachment>_file_name` in the database and also rename the existing file on the filesystem (or S3 or whatever driver). 

If the attachment has yet to be saved it would just simply update `<attachment>_file_name` on that instance.

There are some examples out there how paperclip handles this... but I think if you had this

``` php
$model->attachment->rename('some file.jpg');
```

it would work nicely and is simple enough to use.

**Comment by tabennett** [comment]
This is now implemented in the Dev branch for the upcoming 2.0 release.
