### ISSUE TITLE
S3 storage causing multiple guzzle http requsts.

### ISSUE THREAD

**Issue by tabennett** [CodeSleeve/stapler#53]
Using S3 storage is causing multiple http requests to occur when accessing image urls across a collection of models.  We need to cache the base url for a given bucket once and then use that url to build image paths for subsequent requests.

**Comment by Anahkiasen** [comment]
Is this still the case? I had an issue with an endpoint returning files running out of memory, and doing a Blackfire profile of the endpoint it seems Stapler still does an API request to S3 to get its URL for each file:

![screen shot 2017-11-03 at 11 32 26](https://user-images.githubusercontent.com/1321596/32369748-b3a1fac6-c08a-11e7-889d-59ace9d74185.png)

In this example here, as you can see 64 files are returned, but Stapler seems to call `getObjectUrl` 192 times
