### ISSUE TITLE
Resizer leaves empty temp files

### ISSUE THREAD

**Issue by patrickcarlohickman** [CodeSleeve/stapler#56]
The `resizer->resize()` method starts with the following line:
```
$filePath = tempnam(sys_get_temp_dir(), 'STP') . '.' . $file->getFilename();
```

This uses the `tempnam` function, which actually creates an empty file in the temporary directory, and then returns the file name.  However, the name of this file is only used to help build `$filePath`, which is used for the resized images, and is later moved to the final location.  Unfortunately, the original empty file created by the `tempnam` function is never used or cleaned up, and it gets left behind.

**Comment by tabennett** [comment]
This has now been fixed on master and will be in the next release. Better late than never I suppose. Thanks for the help.
