### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ir0ny1** [CodeSleeve/stapler#59]
Hey, I was wondering where exactly I should validate the image to for example make sure its even an image (otherwise mimetype check crashes). Is there anyway for example to validate hasAttachedFile('photo') from the model itself?

**Comment by dwalker109** [comment]
I just had the same problem - I'm using `dwightwatson/validating` but the principle is the same.

The validation packages are designed to work on the raw files data (typically from `$_FILES`, ultimately). By the time Ardent et. al. get to the validation stage Stapler has nipped in and worked its magic, and the validation fails.

I worked around this with a custom validation rule, which just gets the value straight out of `Input::files()` and validates against that with the normal Laravel rules, like [so](https://gist.github.com/dwalker109/dbae24e2174719551293).

This could be adapted to work on the file as an attribute of the model, I'm sure.

**Comment by tabennett** [comment]
This package assumes that you're handling all validation before you try and save the model. It's not currently made to work work (at least out of the box) with third party validation packages like that.
