### ISSUE TITLE
[Proposal] Accept DataURLs from Javascript

### ISSUE THREAD

**Issue by rtablada** [CodeSleeve/stapler#60]
It would be nice to be able to upload XHR file requests from javascript using the Filereader.readAsDataURL functionality directly into stapler.

From what I've read, `readAsDataURL` formats the file as a base64 encoded string with extra meta-data on the front end of things. It's formatted a bit like `data:[<MIME-type>][;charset=<encoding>][;base64],<data>`

I think that it would be possible to add a regex that matches strings that start with `data`. I know that there is [this package](http://php-datauri.readthedocs.org/en/latest/) to decipher data URI's into something a bit more usable. I'm checking to see if there's a way to shim this into a Symfony uploaded file object to pull the responsibility out of Stapler.

**Comment by hackel** [comment]
Close.  Was fixed in #69c5048.
