### ISSUE TITLE
On uploading file through Stapler I get Symfony \ Component \ HttpFoundation \ File \ Exception \ FileNotFoundException The file "1.png" does not exist

### ISSUE THREAD

**Issue by mdunbavan** [CodeSleeve/stapler#74]
Hi,

I have been using Stapler for ages now.

All of a sudden I get the error above when uploading files now on my local machine.

Is this a bug? Here is the stack trace from the log file:

[2014-05-28 09:40:21] local.ERROR: exception 'Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException' with message 'The file "1.png" does not exist' in /Freelance/Current Projects/mbm-site/laravel/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/File/File.php:41
Stack trace:
#0 /Freelance/Current Projects/mbm-site/laravel/vendor/codesleeve/stapler/src/Codesleeve/Stapler/IOWrapper.php(96): Symfony\Component\HttpFoundation\File\File->__construct('1.png', '1.png')
#1 /Freelance/Current Projects/mbm-site/laravel/vendor/codesleeve/stapler/src/Codesleeve/Stapler/IOWrapper.php(29): Codesleeve\Stapler\IOWrapper->createFromString('1.png')
#2 /Freelance/Current Projects/mbm-site/laravel/vendor/codesleeve/stapler/src/Codesleeve/Stapler/Attachment.php(129): Codesleeve\Stapler\IOWrapper->make('1.png')
#3 /Freelance/Current Projects/mbm-site/laravel/vendor/codesleeve/stapler/src/Codesleeve/Stapler/Stapler.php(123): Codesleeve\Stapler\Attachment->setUploadedFile('1.png')
#4 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(340): Post->setAttribute('hero_image', '1.png')
#5 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1326): Illuminate\Database\Eloquent\Model->fill(Array)
#6 /Freelance/Current Projects/mbm-site/laravel/app/controllers/PostsController.php(157): Illuminate\Database\Eloquent\Model->update(Array)
#7 [internal function]: PostsController->update('85')
#8 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#9 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('update', Array)
#10 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(PostsController), Object(Illuminate\Routing\Route), 'update')
#11 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'PostsController', 'update')
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}('85')
#13 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(105): call_user_func_array(Object(Closure), Array)
#14 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 /Freelance/Current Projects/mbm-site/laravel/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 /Freelance/Current Projects/mbm-site/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 /Freelance/Current Projects/mbm-site/laravel/public/index.php(49): Illuminate\Foundation\Application->run()
#25 /Freelance/Current Projects/mbm-site/laravel/server.php(19): require_once('/Freelance/Curr...')
#26 {main} [] []

Cheers,
Mark

**Comment by pursuantsolutions** [comment]
Same issue, but I was using form helpers... so adding:
    'files'=>true
fixed my issue...
