### ISSUE TITLE
Saving files: jpeg encoded image data / data URI scheme

### ISSUE THREAD

**Issue by Gelurban** [CodeSleeve/stapler#81]
Is it possible to save an encoded image instead of giving a image file path / url ?

For example, it would be nice to be able to do 

$post->image= $encoded_image_data;
$post->save();

Because of the fact that my javascript app posts an "data:image/jpeg;base64" image to my controller.

Thanks in advance

**Comment by hackel** [comment]
Close. Was fixed in 69c5048.
