### ISSUE TITLE
Save the thumbnails generated at runtime

### ISSUE THREAD

**Issue by Anahkiasen** [CodeSleeve/stapler#84]
Currently, unless I misconfigured something, when you view a page which has a thumbnail that wasn't prerendered, it'll generate it on the fly but won't save it in the corresponding folder. Meaning if you refresh the page it'll rerender it again. Couldn't those be saved ?

**Comment by tabennett** [comment]
Stapler generates all of its styles after save (there's no on the fly generation, but I guess you know this by now).
