### ISSUE TITLE
How to check if a file is attached?

### ISSUE THREAD

**Issue by EloProf** [CodeSleeve/stapler#91]
I have searched in the Doc and in the Issues over here on GitHub, but i can't find anything about how you check if there actually is a file attached?

I thought it would be something along the lines of
```php
\is_null($model->file);
```
or
```php
$model->file->exists();
```
Unfortunately I can't find anything about this.

**Comment by tabennett** [comment]
@kjmeath Yeah, that's how I do it as well.  I think this is currently the best way to check to see if a file has been uploaded.

**Comment by otagi** [comment]
It would be nice to have an `exists` method that just checks `originalFilename`, though. (for improved code readability)

**Comment by EloProf** [comment]
In my opinion it would be logically better to just have the file attribute just be `null` when it doesn't exist. This is probably the instinctively expected behaviour of most programmers. It is very uncommon and actually makes logically very little sense that an object, in this case the `Attachment`, exists as a representation for something that isn't actually there in the first place.

**Comment by tabennett** [comment]
That doesn't make sense though.  There would be no way to display a default file, because the attachment object wouldn't exist yet.  Right now, you can configure a default file path for any attachment.  So, for example if a user hasn't uploaded an avatar yet, you can still display (and configure) a default photo in a standardized way.

**Comment by EloProf** [comment]
Hm okay I understand that use case. In this case it actually makes sense, that the attachment object exists because it will always represent something else.

How about changing it so that the attachment is `null` if there is not default set. With this the standard test of `is_null($model->attachment)` would make perfect sense in all cases, because if there is a default attachment set, then it should exist, and you can actually do something with it. But the case of the useless unset `Attachment` object I mentioned would be completly removed.
